### ISSUE TITLE
Need to use MVC pattern

### ISSUE THREAD

**Issue by anil826** [bappygolder/oTask#108]
Currently all images are on the root of application which not look good as developer point it's need to use in separated file i suggest please use Model- View - Controller pattern.

**Comment by bappygolder** [comment]
Thanks @anil826. This is something that needs fixing. Do you think you can work on that part? Currently the images are working for desktop, android and iphone. We need to make sure it still works but need to improve the file structure.

**Comment by creativein** [comment]
@bappygolder This issue is resolved . You can test it on android device and apple devices after merging the pull-request.

**Comment by bappygolder** [comment]
Needs testing in all devices.
