### ISSUE TITLE
OT31 - List items (data) not persisting after browser is refreshed. 

### ISSUE THREAD

**Issue by bappygolder** [bappygolder/oTask#31]
We need list items to persist for a same device. Even if the user refreshes the browser user data will persist. Data will only be emptied if:
1. User opens a new instant of the web page or the link or
3. If the user presses the clear button.

**Comment by anil826** [comment]
I will do this for you .

**Comment by bappygolder** [comment]
Fantastic Anil. I'd appreciate if you could fill out this form for this task: 
https://bappy.typeform.com/to/rNtiON

I'll be able to hire you after that. Cheers.

**Comment by anil826** [comment]
Thank you I am happy to work with you ..

**Comment by mayurbhavsar45** [comment]
I am looking into this problem. Let's see how I go ...

**Comment by bappygolder** [comment]
Thanks @mayurbhavsar45. appreciate the help. Guys can you all please pause the work on this as Mayur is tackling this right now. Cheers

@anil826 Can you try working on another issue as a test please?

**Comment by mayurbhavsar45** [comment]
Hello Bappy,

I solved this issue and test it . its properly working as we discuss.

**Comment by TalhaAkbar** [comment]
Glad to know @mayurbhavsar45 solved the problem. I did as well. @bappygolder, you can discuss it with him first. I am open to other work if available.

**Comment by bappygolder** [comment]
Issue fixed and implemented to **gh-pages**. Reviewed by @mayurbhavsar45 & myself.
