### ISSUE TITLE
OT38 - Remove internal scrollbar from the list

### ISSUE THREAD

**Issue by bappygolder** [bappygolder/oTask#38]
With the new structure of the app the internal scrollbar is now redundant. It seems to cause poor UX now. This can be removed.

**Comment by anil826** [comment]
But after remove internal scrollbar how user can delete task list when task list is greater than 8+ . suppose user want to delete last task.. then.?

**Comment by bappygolder** [comment]
In this case we'll have to make the clear button not sticky. But I think another person is also looking at the issue.

**Comment by bappygolder** [comment]
Implimented: https://github.com/bappygolder/oTask/pull/88
