### ISSUE TITLE
OT39 - Add links to the information from the empty task view. 

### ISSUE THREAD

**Issue by bappygolder** [bappygolder/oTask#39]
Add some links to the empty list view so the users can navigate to the information websites.

**Comment by bappygolder** [comment]
The green button on the empty task page can say "About oTask" and can link to the website.

**Comment by bappygolder** [comment]
Link to add: http://otask.tumblr.com/about

**Comment by anil826** [comment]
Link button is added now and changes is deploy on master-OT39 branch please check and merge it.

**Comment by bappygolder** [comment]
Anil are you working from a fork? I never see your pull requests. Pleas make a fork if you haven't yet already and you should be able to do everything from github desktop.

**Comment by anil826** [comment]
Done: https://github.com/bappygolder/oTask/pull/88

**Comment by bappygolder** [comment]
So it seems the button works well. I merged to to live. I think we need to add a `target="_blank"` or something so that it opens in a new tab. What do you think?

If it is doable can you implement that at some point and send me a pull request. I don't know how to do it on a function.

**Comment by bappygolder** [comment]
Well done @anil826. Thanks for solving this issue.
