### ISSUE TITLE
OT45 - Mobile phone keyboard issue fix

### ISSUE THREAD

**Issue by bappygolder** [bappygolder/oTask#45]
At the moment when people add a tasks the keyboard on the phone screen disappear. We want the keyboard to stay on the screen and the input field to be on focus so the users can easily start typing.

**Comment by mayurbhavsar45** [comment]
I am working on this .

**Comment by mayurbhavsar45** [comment]
I have done this task.

**Comment by bappygolder** [comment]
Issue fixed.
