### ISSUE TITLE
Update place holder text on focus

### ISSUE THREAD

**Issue by bappygolder** [bappygolder/oTask#55]

**Comment by creativein** [comment]
@bappygolder  I am working on this issue.

**Comment by bappygolder** [comment]
Thanks @FroyoAndroid look forward to discuss updates tomorrow.

**Comment by creativein** [comment]
@bappygolder  The Pull Request has been generated for this Issue. You can review the changes.

**Comment by bappygolder** [comment]
Reviewed and implemented to gh-pages
